import { PrismaClient } from '@prisma/client';
import { PrismaD1 } from '@prisma/adapter-d1';

interface Env {
  DB: D1Database;
  GITHUB_TOKEN: string;
}

interface QueueMessage {
  jobId: string;
}

// Function to parse GitHub repo URL
function parseGitHubUrl(url: string): { owner: string; repo: string } | null {
  const match = url.match(/github\.com\/([^\/]+)\/([^\/]+)/);
  if (match) {
    const repoName = match[2].endsWith('.git') ? match[2].slice(0, -4) : match[2];
    return { owner: match[1], repo: repoName };
  }
  return null;
}

// Helper to fetch raw file content from GitHub
async function getFileContent(owner: string, repo: string, path: string, githubToken: string): Promise<string | null> {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
    try {
        const response = await fetch(url, {
            headers: {
                'Authorization': `token ${githubToken}`,
                'User-Agent': 'CloudCurio-Review-Worker',
                'Accept': 'application/vnd.github.v3.raw',
            },
        });
        if (!response.ok) {
            return null;
        }
        return await response.text();
    } catch (e) {
        console.error(`Failed to fetch file content for ${path}:`, e);
        return null;
    }
}

// Performs a simple analysis of file content
function analyzeContent(content: string): { lineCount: number; todoCount: number } {
    const lines = content.split('\n');
    const todoCount = (content.match(/TODO/gi) || []).length;
    return { lineCount: lines.length, todoCount };
}

// Generates an HTML report based on the analysis
async function generateReport(repoUrl: string, githubToken: string): Promise<string> {
  const repoInfo = parseGitHubUrl(repoUrl);
  if (!repoInfo) {
    return '<h1>Unsupported Repository URL</h1><p>Only GitHub repositories are supported at this time.</p>';
  }

  const { owner, repo } = repoInfo;
  const filesToAnalyze = ['package.json', 'README.md'];
  let analysisHtml = '';

  for (const filePath of filesToAnalyze) {
    const content = await getFileContent(owner, repo, filePath, githubToken);
    if (content) {
      const analysis = analyzeContent(content);
      analysisHtml += `
        <h3>${filePath}</h3>
        <ul>
          <li>Line Count: ${analysis.lineCount}</li>
          <li>"TODO" Mentions: ${analysis.todoCount}</li>
        </ul>
      `;
    } else {
      analysisHtml += `<h3>${filePath}</h3><p>Could not be analyzed (file might not exist or is inaccessible).</p>`;
    }
  }

  let fileListHtml = 'Could not retrieve file list.';
  try {
    const contentsUrl = `https://api.github.com/repos/${owner}/${repo}/contents`;
    const response = await fetch(contentsUrl, {
      headers: {
        'Authorization': `token ${githubToken}`,
        'User-Agent': 'CloudCurio-Review-Worker',
        'Accept': 'application/vnd.github.v3+json',
      },
    });

    if (response.ok) {
      const files: any[] = await response.json();
      fileListHtml = files.map((file) => `<li>${file.name} (${file.type})</li>`).join('');
    }
  } catch (e) {
    console.error('Failed to fetch repository file list:', e);
  }

  return `
    <h1>Cloudflare Worker Review</h1>
    <p>This is a simplified analysis report generated by a Cloudflare Worker.</p>
    <h2>Analysis of Key Files</h2>
    ${analysisHtml}
    <h2>Repository File Listing</h2>
    <ul>${fileListHtml}</ul>
  `;
}

export default {
  async queue(
    batch: MessageBatch<QueueMessage>,
    env: Env,
    ctx: ExecutionContext
  ): Promise<void> {
    const adapter = new PrismaD1(env.DB);
    const prisma = new PrismaClient({ adapter });

    for (const message of batch.messages) {
      const { jobId } = message.body;
      let job;

      try {
        job = await prisma.reviewJob.findUnique({ where: { id: jobId } });
        if (!job) {
          console.error(`Job ${jobId} not found.`);
          message.ack();
          continue;
        }

        await prisma.reviewJob.update({
          where: { id: jobId },
          data: { status: 'processing' },
        });

        const reportContent = await generateReport(job.repoUrl, env.GITHUB_TOKEN);

        await prisma.reviewArtifact.create({
          data: {
            jobId: jobId,
            content: reportContent,
          },
        });

        await prisma.reviewJob.update({
          where: { id: jobId },
          data: {
            status: 'done',
            resultUrl: `/reviews/${jobId}`,
          },
        });

        message.ack();

      } catch (error: any) {
        console.error(`Failed to process job ${jobId}:`, error);

        const existingMeta = job?.meta ? JSON.parse(job.meta) : {};
        const newMeta = { ...existingMeta, error: 'Worker processing failed', errorMessage: error.message };

        if (job) {
            await prisma.reviewJob.update({
              where: { id: jobId },
              data: {
                status: 'error',
                meta: JSON.stringify(newMeta),
              },
            });
        }
        message.retry();
      }
    }
  },
};