name: Python Worker Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'worker/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'worker/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd worker
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        run: |
          cd worker
          python -m pytest tests/ -v